### ISSUE TITLE
Exchange data between R and Ruby

### ISSUE THREAD

**Issue by agisga** [yihui/runr#20]
Is it possible to exchange information between R and a Ruby process?

I am aware that I can do something like this:

```{r}
rb = proc_ruby()
rb$start()

rb$exec("a = 1..8", "a")
ruby_out <- as.numeric(rb$exec("print a.inject(:+)")[[2]])
ruby_out
# [1] 36

rb$stop()
```

but that seems like a hack to me.

Is there a more direct way to save Ruby results (such as Float, Strings, Array) as R objects?

If that's currently not possible, I would appreciate it if somebody can give me a pointer of how something like that can be implemented.

**Comment by yihui** [comment]
That will be way more work to do and is beyond the scope of **runr** (I don't have the technical skills). Here is an early implementation: http://www.omegahat.net/RRuby/ Take a look at its date before you decide whether you want to try it :)

**Comment by agisga** [comment]
Thanks! I'll take a look at RRuby.
