### ISSUE TITLE
Is it possible integrate python with reticulate into knitr?

### ISSUE THREAD

**Issue by harryprince** [yihui/runr#23]
Integrate Python into knitr sounds like great, however, using current runr solution is a little bit redundant. A better way may be just run Python code like R code as usual.

I have try the reticulate solution, like this:

```
\```{r}
knitr::knit_engines$set(python = reticulate::eng_python)
knitr::opts_chunk$set(cache = T)
knitr::opts_chunk$set(engine='python') 

\```
```

```
\```{python}
a= 1
\```
```
```
\```{python}
print(a)
\```
```

```
NameError: name 'a' is not defined
```

It seems knitr could not transfer the cache with reticulate

## references

* https://www.rdocumentation.org/packages/reticulate/versions/1.3/topics/eng_python
* http://rpubs.com/badbye/python-knitr

**Comment by yihui** [comment]
Don't use the runr package. Just [update to the lastest version](https://yihui.name/en/2017/05/when-in-doubt-upgrade/) of knitr: https://github.com/yihui/knitr/releases

Caching is going to be tricky. It is more of an issue for reticulate instead of knitr: https://github.com/rstudio/reticulate
