### ISSUE TITLE
how to set up julia to use runr?

### ISSUE THREAD

**Issue by ravinder387** [yihui/runr#26]
I got error that julia is not installed or not in path.. I'm using ubuntu

**Comment by yihui** [comment]
I recommend you to use [the **JuliaCall** package](https://github.com/Non-Contradiction/JuliaCall) instead. This **runr** package was experimental, and is unlikely to be formally released. Thanks!

BTW, if you use R Markdown, there is a `julia` engine based on **JuliaCall**: https://bookdown.org/yihui/rmarkdown/language-engines.html#julia

**Comment by ravinder387** [comment]
thank you Sir

**Comment by yihui** [comment]
You are welcome!
